config/routes.rb
Rails.application.routes.draw do

  root 'uploads#index'
  resources :uploads
  resources :games

end

app/models/play.rb
class Play < ActiveRecord::Base
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  has_attached_file :file, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_presence :file
  validates_attachment_content_type :file, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  def self.create_with_file(uploads)
    return if uploads.blank?
    uploads[:file].each do |upload_file|
      Upload.create(file: upload_file)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :new
  before_action :all_plays, only: [:index, :new]
  def index
    @uploads = Upload.all
  end

  def new
    play =  Play.new(game_params)
    play.save
  end

  private

  def game_params
    {path: params[:path], counter: params[:count]}
  end

  def all_plays
    @plays = Play.all
  end

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController

  def index
    @upload = Upload.new
  end

  def create
    redirect_to root_path, flash: {notice: "Please select image"} and return unless params[:upload].present?
    Upload.create_with_file(upload_params)
    redirect_to root_path, flash: {notice: "Uploaded."}
  end

  private

  def upload_params
    params.require(:upload).permit(file: [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/games/_image_table.html.erb
<h1>Your all players</h1>
<div>
  <%-@plays.each do |play|%>
    <table class="player-table">
      <tr>
        <td class="play-image">
          <%= image_tag play.path %>
        </td>
        <td>
          <%= play.counter %>
        </td>
      </tr>
    </table>
  <%end%>
</div>

app/views/games/index.html.erb
<% if @uploads.any?%>
	<h1 id="timer"></h1>
	<div id="image">
	  
	</div>
	<div id="plays">
		<%= render :partial => "image_table"%>
	</div>
	<%- @uploads.each do |upload|%>
	  <input class="uploads" name="uploads[]" type="hidden" value="<%= upload.file %>"></input>
	<%end%>
	<script type="text/javascript">
	  get_all_uploads();
	</script>
<%else%>
	<h5>No uploads</h5>
<%end%>

app/views/games/new.js.erb
<%= render :partial => "image_table" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlayerImages</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "shared/menu"%>
	<%= render "shared/error_messages"%>
	<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if flash[:notice]%>
  <h6><%= flash[:notice]%></h6>
<%end%>

app/views/shared/_menu.html.erb
<h4>
  <span><%= link_to "Play Game", games_path%></span>
  <span><%= link_to "Upload Images", root_path%></span>
</h4>

app/views/uploads/index.html.erb
<h6>Upload Images (Supported content type image/jpg, image/jpeg and image/png)</h6>
<%= form_for @upload do |form| %>
  <%= form.file_field :file, multiple: true %>
  <%= form.submit %>
<% end %>